### PR TITLE
Pure Haskell UTF parser for `unescapeText`.

### PR DESCRIPTION
**Pull request by jprider63**
#450

### CODE REVIEW

**Comment by bergmark** [comment]
Good stuff, thanks!

Like i mentioned in #450 it'd be nice to have this in separate module.
That way both unit tests and benchmarks can be run against both implementations without needing a rebuild. 

I can look into that this week.

**Comment by jprider63** [comment]
Sorry, I missed that request initially. I've split them into separate modules. I think you'll still need to rebuild to test and benchmark though.

**Comment by bergmark** [comment]
I rebased this on top of the `unescape` branch along with other changes but a test fails on travis. I wasn't able to reproduce it locally: https://travis-ci.org/bos/aeson/jobs/203164303#L859

**Comment by jprider63** [comment]
This looks like FromJSONKey? This test fails for me on the main branch (d470ac6), so I assumed it was fine.

**Comment by bergmark** [comment]
Very strange, I haven't seen that error before

**Comment by jprider63** [comment]
It is odd. I've uploaded the [failed logs](http://lpaste.net/3696006614487138304) from master in case you want to see it. How should we proceed?

**Comment by bergmark** [comment]
Thanks for following up!

Are you able to debug this locally? It would be very helpful since I haven't been able to reproduce it.

Even if we don't figure out how to fix this it would be good to know the severity; Any particular things to avoid / any workarounds? Will it cause bugs?

Since no one has mentioned being affected by this when using the library maybe we could release this with a disclaimer, but I think we should make sure that we get the test suite passing on travis again.

**Comment by bergmark** [comment]
Resolved thanks to @Lysxia!

Rebased @ f16a7f5. I'm releasing now.

**Pull request closed without merging**
