### PR TITLE
Bumped version of QuickCheck

### PR DESCRIPTION
**Pull request by coot**
Allow QuickCheck-2.12

### CODE REVIEW

**Comment by bergmark** [comment]
Thanks! restarted one of the build steps.

**Comment by bergmark** [comment]
`tests/Properties.hs` takes a long time to compile on GHC 8.6, travis consistently kills it. It's also slow for me locally, but it does finish eventually.

We haven't seen this issue on master so that makes the new QuickCheck look suspicious...

**Comment by coot** [comment]
In my setup I get:
```
time cabal new-test --ghc-option="-fforce-recomp"
cabal new-test --ghc-options "-fforce-recomp"  376.50s user 4.33s system 100% cpu 6:20.46 total
```
```
ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.6.0.20180714
```
Which version of quickcheck are you compiling against?

**Comment by bergmark** [comment]
I merged #684 which sped up compilation time, it's a mystery why travis consistently failed here...

**Comment by coot** [comment]
Thanks!

**Pull request closed without merging**
