### PR TITLE
Support GHC 8.8

### PR DESCRIPTION
**Pull request by fumieval**
Pardon an automatically-posted pull request; this is a part of [Operation Vanguard](https://github.com/haskell-vanguard/haskell-vanguard). Note that this does not guarantee that tests and benchmarks are buildable.

### CODE REVIEW

**Comment by bergmark** [comment]
Thanks! Cool project, so vanguard verifies that the library builds? Is there a reason you don't build tests and benchmarks? (Running them could be more complicated so that makes sense).

We should add ghc 8.8 to the travis CI job before merging this, looks like it's available there now. I'll hopefully get around to it soon if no one beats me to it.

**Comment by bergmark** [comment]
There are some dependencies needed before we can get (mainly the test-suite) building on 8.8: dlist, integer-logarithms, attoparsec, optparse-applicative (and maybe more that I missed).

**Comment by asr** [comment]
Blocking https://github.com/agda/agda/issues/3725.

**Comment by phadej** [comment]
I think the code is adjusted, only bounds need to be relaxed. So `--allow-newer=aeson` should "just work".

**Comment by phadej** [comment]
The `aeson` library dependencies are updated, except `dlist`. https://github.com/spl/dlist/issues/34

tests/benchmarks need updates (at least `microstache`, which I'll update once `dlist` is updated).

**Comment by AndreasPK** [comment]
dlist has been updated.

**Comment by RyanGlScott** [comment]
It appears that `aeson-1.4.4.0` was [revised](http://hackage.haskell.org/package/aeson-1.4.4.0/revisions/) to permit `template-haskell-2.15.0.0` and `time-1.9`. In light of this, is this PR still necessary, or can it be closed?

**Comment by phadej** [comment]
Ryan: you are right. There are some “feature full” commits after 1.4.4.0 tag, but aeson compiles with GHC-8.8 without them as well.

Adam: thanks for the revision.

Let me see what I can release/review myself now...

**Comment by bergmark** [comment]
Thanks.

**Pull request closed without merging**
