### PR TITLE
Resolve #311

### LINKED ISSUE #311: Enclosing member names in JSONPath
Current, `aeson-0.10.0.0`
````haskell
Prelude M A> A.eitherDecode "{\"a.b\" : \"c\"}" :: Either String (M.HashMap String Int)
Left "Error in $.a.b: expected Int, encountered String"
````

Expected [[ref](https://groups.google.com/forum/#!topic/jsonpath/7YvgXWP1_7Y)]
````haskell
Prelude M A> A.eitherDecode "{\"a.b\" : \"c\"}" :: Either String (M.HashMap String Int)
Left "Error in $.['a.b']: expected Int, encountered String"
````

A `key`, regardless of its contents, if defensively enclosed as `['key']`, solves this problem. Otherwise, presence of `.` can be tested and `key` can be enclosed accordingly.

### PR DESCRIPTION
**Pull request by phadej**
```
> putStrLn $ formatError [Index 0, Key "foo", Key "bar", Key "a.b.c", Key "", Key "'\\", Key "end"] "error msg"
Error in $[0].foo.bar['a.b.c']['']['\'\\'].end: error msg
```

### CODE REVIEW

**Comment by bergmark** [comment]
Looks good, thanks! Can you please add some tests for this?

**Comment by phadej** [comment]
I don't know why GHC8.0 build suddenly failed.

**Comment by hvr** [comment]
@phadej the GHC 8.0 ppa snapshot was updated last night, and this required a travis cache wipe... this will get more robust with `cabal new-build`

**Comment by bergmark** [comment]
:+1:

**Pull request merged**
