### PR TITLE
Build also with stack on travis (benchmarks)

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by hvr** [comment]
sadly this results in less readable travis log-output as you can't collapse the sections anymore

**Comment by phadej** [comment]
@hvr, that's true :(

**Comment by phadej** [comment]
Alternatively we could merge benchmarks into `aeson` package, if there aren't really good reason why they are separate package?

**Comment by bergmark** [comment]
Can't, the benchmarks have dependencies like statistics that depend on aeson

**Comment by phadej** [comment]
finally green

**Comment by hvr** [comment]
@bergmark re cyclic deps, see https://github.com/haskell/cabal/pull/3422

**Comment by mgsloan** [comment]
Stack has actually supported cyclic deps for quite some time, though it gets a little dicey with older Cabals due to https://github.com/haskell/cabal/issues/2870

**Pull request merged**
