### PR TITLE
Add GHC-8.8.1 Travis job

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by phadej** [comment]
Can someone restart 8.8.1 job, `quickcheck-instances` and `hashable-time` should be fine now.

**Comment by bergmark** [comment]
Hmm

```
+cabal install --only-dependencies --enable-tests --enable-benchmarks --dry -v
CallStack (from HasCallStack):
  die', called at ./Distribution/Client/CmdInstall.hs:233:5 in main:Distribution.Client.CmdInstall
cabal: --enable-tests was specified, but tests can't be enabled in a remote
``

**Comment by phadej** [comment]
Travis is turning green.

**Comment by phadej** [comment]
ping @bergmark

**Comment by bergmark** [comment]
Nice!

**Comment by phadej** [comment]
I hope to see `aeson` release soon, it would keep me busy updating revdeps for MuniHac!

**Comment by bergmark** [comment]
I can/should make a release soon, but are you unblocked with the revision @phadej?

**Comment by phadej** [comment]
@bergmark, yes I am. No pressure from my side

**Pull request merged**
