### PR TITLE
Instances for Void/V1

### PR DESCRIPTION
**Pull request by wyager**
re https://github.com/bos/aeson/issues/661

Create instances for Void/V1

### CODE REVIEW

**Comment by phadej** [comment]
look up for `build-depends: nats`:

```
  if !impl(ghc >= 7.10)
    build-depends:
      void >= 0.7.2 && < 0.8
```

---

`EmptyCase` is GHC-7.8+

---

```diff
diff --git a/Data/Aeson/Types/ToJSON.hs b/Data/Aeson/Types/ToJSON.hs
index c9b8053..5765655 100644
--- a/Data/Aeson/Types/ToJSON.hs
+++ b/Data/Aeson/Types/ToJSON.hs
@@ -14,7 +14,6 @@
 {-# LANGUAGE TypeOperators #-}
 {-# LANGUAGE TypeSynonymInstances #-}
 {-# LANGUAGE UndecidableInstances #-}
-{-# LANGUAGE EmptyCase #-}
 
 #if __GLASGOW_HASKELL__ >= 706
 {-# LANGUAGE PolyKinds #-}
@@ -92,7 +91,7 @@ import Data.Time.Format (FormatTime, formatTime)
 import Data.Time.Locale.Compat (defaultTimeLocale)
 import Data.Vector (Vector)
 import Data.Version (Version, showVersion)
-import Data.Void (Void)
+import Data.Void (Void, absurd)
 import Data.Word (Word16, Word32, Word64, Word8)
 import Foreign.Storable (Storable)
 import Foreign.C.Types (CTime (..))
@@ -707,7 +706,7 @@ instance ( AllNullary       (a :+: b) allNullary
 instance GToJSON Value arity V1 where
     -- Empty values do not exist, which makes the job of formatting them
     -- rather easy:
-    gToJSON _ _ x = case x of {}
+    gToJSON _ _ x = x `seq` error "case: V1"
     {-# INLINE gToJSON #-}
 
 instance ToJSON a => GToJSON Value arity (K1 i a) where
@@ -1230,10 +1229,10 @@ instance (ToJSON a, ToJSON b) => ToJSON (Either a b) where
     {-# INLINE toEncoding #-}
 
 instance ToJSON Void where
-    toJSON x = case x of {}
+    toJSON = absurd
     {-# INLINE toJSON #-}
 
-    toEncoding x = case x of {}
+    toEncoding = absurd
     {-# INLINE toEncoding #-}
 
 
diff --git a/aeson.cabal b/aeson.cabal
index d251478..1a6f32d 100644
--- a/aeson.cabal
+++ b/aeson.cabal
@@ -135,7 +135,8 @@ library
 
   if !impl(ghc >= 7.10)
     -- `Numeric.Natural` is available in base only since GHC 7.10 / base 4.8
-    build-depends: nats >= 1 && < 1.2
+    build-depends: nats >= 1 && < 1.2,
+                   void >= 0.7.2 && < 0.8
 
   ghc-options: -Wall
 
@@ -227,7 +228,8 @@ test-suite tests
       transformers-compat >= 0.3
 
   if !impl(ghc >= 7.10)
-    build-depends: nats >=1 && <1.2
+    build-depends: nats >=1 && <1.2,
+                   void >=0.7.2 && <0.8
 
   if impl(ghc >= 7.8)
     build-depends: hashable-time >= 0.2 && <0.3
```

**Comment by bergmark** [comment]
Thanks! I can apply @phadej's patch when merging this.

**Comment by wyager** [comment]
Want me to just add these changes to my fork and update the pull request?

**Comment by bergmark** [comment]
I pushed it to your branch.

**Pull request merged**
