### PR TITLE
Create iso8601-attoparsec package

### PR DESCRIPTION
**Pull request by bergmark**

### CODE REVIEW

**Comment by bergmark** [comment]
#507

**Comment by hvr** [comment]
@bergmark out of curiousity: why `iso8601-attoparsec` rather than `attoparsec-iso8601`? I've been wondering about naming conventions for some time now, and when two packages are affected, which package name to put first in a hybrid package.

**Comment by bergmark** [comment]
> iso8601-attoparsec rather than attoparsec-iso8601? 

It was @phadej's suggestion and I don't have a strong preference, but I agree that flipping the words makes sense.

**Comment by bergmark** [comment]
Whoops, I accidentally requested a review from Bryan...

**Comment by hvr** [comment]
@bergmark this is rather GitHub's automatic reviewer-suggestion feature which auto-adds reviews inferred from  `git blame`  data...

**Comment by bergmark** [comment]
Well i clicked it to see why his name was there and then that happened :-P

**Pull request merged**
