### PR TITLE
Clarify the treatment of Maybe fields, fix the examples

### PR DESCRIPTION
**Pull request by feuerbach**

### CODE REVIEW

**Comment by bergmark** [comment]
Oh, looks like there is an issue with the latest tasty-golden on old GHCs.

**Comment by bergmark** [comment]
Eh it wasn't introduced by this PR anyway, so let's merge!

**Comment by feuerbach** [comment]
Thanks for the quick merge Adam — good to hear from you as well!

I'll re-add support for 7.8.4 shortly.

**Comment by feuerbach** [comment]
Actually, it might even pass if you just restart the job, thanks to the cabal file revision by @phadej.

**Pull request merged**
