### PR TITLE
Encoding refactoring final

### PR DESCRIPTION
**Pull request by phadej**
The last commit particularly makes encoding a tagged type (Maybe we could have `TaggedEncoding tag` and `type Encoding = TaggedEncoding Value`)

There are only few tags (`Value`, `Text` and `T`), but more can be introduced if we feel so, none of `Instances` non-generic code need anything else (in particular tags could help to track what kind of Encoding we are assembling in generic code - dunno if that helps, cc @RyanGlScott ).

### CODE REVIEW

**Comment by phadej** [comment]
*Refactor ToJSONKeyFunction, add some docs* resolves #416

**Comment by bergmark** [comment]
Looks like an actual test failure on travis

**Comment by phadej** [comment]
force pushed, let's see.

**Comment by bergmark** [comment]
This needs a rebase now

**Comment by phadej** [comment]
rebased

**Pull request merged**
