### PR TITLE
Add DList instances and some roundtrip key tests

### PR DESCRIPTION
**Pull request by phadej**
Resolve https://github.com/bos/aeson/issues/401

These should be straightforward

### CODE REVIEW

**Comment by andrewthad** [comment]
Quick question. In the `FromJSONKey` instance for `Bool`:

    fromJSONKey = FromJSONKeyTextParser $ \t -> case t of
        "true"  -> pure True
        "false" -> pure False
        _       -> fail $ "Cannot parse key into Bool: " ++ T.unpack t

How are you pattern matching on `Text`? I've never seen this before.

**Comment by phadej** [comment]
@andrewthad the same way as e.g. with `Num`, using `Eq` instance:
```
λ Prelude > :set -XOverloadedStrings 
λ Prelude > :t \x -> case x of { "" -> True; _ -> False }
\x -> case x of { "" -> True; _ -> False }
  :: (Data.String.IsString a, Eq a) => a -> Bool
```

**Comment by bergmark** [comment]
@andrewthad -XOverloadedStrings allows this.

**Comment by andrewthad** [comment]
Good to know.

**Pull request merged**
