### PR TITLE
Add flag for benchmarks to select local or external aeson dependency

### PR DESCRIPTION
**Pull request by Lysxia**
Avoids the duplication due to executables integrating two versions of aeson at the same time.

### CODE REVIEW

**Comment by bergmark** [comment]
I pushed a hlint fix

**Comment by bergmark** [comment]
Thanks!

**Comment by phadej** [comment]
I really dislike this. Now it's way harder to see regressions against released `aeson`. The setup was complicated, but there was a reason.

**Comment by phadej** [comment]
Note: I know that someone (read: me) should have documented how to benchmark aeson, as the setup _is_ complicated, and not just `stack bench`. I would have done that, as I saw the activity around that code, haven't time to go thru notifications earilier this week.

**Comment by Lysxia** [comment]
Is it really harder now? We can build benchmarks with development or released versions of aeson by switching a flag.

**Comment by phadej** [comment]
See e.g. https://github.com/bos/aeson/pull/561#issuecomment-315108405

**Comment by phadej** [comment]
These graphs (and other stats criterion renders html) are very useful, at least for me. Text output isn't as good.

**Comment by Lysxia** [comment]
Okay. I think it would be nicer to make criterion render data from multiple sources than maintaining two copies of the same code.

**Pull request merged**
