### PR TITLE
Add Compose instances, correct Identity

### PR DESCRIPTION
**Pull request by phadej**
Part of resolving https://github.com/bos/aeson/issues/408

I made identity be fully transparent in encoding, i.e. `Compose Identity Identity [Identity (Identity (Compose Identity Identity (Identity Char)))]` should encode as `String`

### CODE REVIEW

**Comment by phadej** [comment]
Good catch about the key!

**Comment by phadej** [comment]
travis failed because of network errors

**Comment by bergmark** [comment]
Needs a rebase

**Comment by phadej** [comment]
rebased

**Comment by bergmark** [comment]
Needs another rebase T_T

**Comment by phadej** [comment]
rebased

**Pull request merged**
