### PR TITLE
Option to encode single-constructor types as tagged sums

### PR DESCRIPTION
**Pull request by Lysxia**
As suggested in #206  and possibly #473

### CODE REVIEW

**Comment by bergmark** [comment]
Github showed the already merged PR's in the history so i force pushed a rebase.

**Comment by bergmark** [comment]
Thanks again, This looks good as well!

Unavoidably this is a breaking change due to the `Options` constructor being exposed. I'll file an issue for un-exposing in the next major along with this to avoid this in the future.

I'll cut a release with the other PR's tomorrow and then merge this.

**Comment by bergmark** [comment]
Looks like i also confused myself and travis by doing "git push origin Lysxia/feature-474" so don't mind the test failure!

**Comment by bergmark** [comment]
I noticed that the new field needs to be added to the `Show Options` instance. I added a regression test so rebasing this PR should break. This should be rebased on top of #526, but let's save some effort and wait for that to get merged!

**Comment by bergmark** [comment]
#526 was merged so this can be rebased.

**Comment by bergmark** [comment]
Same here, I didn't get notified of the recent changes.

Thanks a lot for this!

**Comment by Lysxia** [comment]
Okay! You're welcome!

Actually this patch may lead to some serious regressions because I've introduced an actual loop in the generic implementation. We can probably avoid it by tracking the new option at the type level, as a parameter of the `GToJSON` type class, or by splitting that class in some way.

**Comment by Lysxia** [comment]
This is now just two simple overlapping instances instead of the previous recursive mess.

Ready to merge.

**Comment by bergmark** [comment]
Great stuff!

**Pull request merged**
