### PR TITLE
Add labels to json object and list parsing

### LINKED ISSUE #558: Uninformative invalid JSON error
> Error in $: Failed reading: satisfy

I had an issue today where I saw this error. Having never seen it before it took me some time to track down what my problem was.

It was a simple case of my JSON not being valid after me making an innocent minor change after already checking for validity. Is it possible for Aeson to at least state that the attempted parse failed because the supplied JSON is invalid.

If someone could point to the place where this is handled I could have a go at doing it myself?

Orignally discussed here: https://github.com/bos/aeson/issues/113#issuecomment-311925548

### PR DESCRIPTION
**Pull request by FintanH**
Fixes #558 

This PR adds better error messages to the parsing of objects and lists.

I'm aware of #559 but this change seems more to the point of giving a better message :)

### CODE REVIEW

**Comment by bergmark** [comment]
Thanks a lot! 

It would be really nice to have some tests for this, do you think you have time to add them? Probably in `tests/ErrorMessages.hs`. I'm sure it works but I can't really tell from the code :-) I was thinking about doing a release later this week so I can add them then otherwise.

Also hlint is nitpicking a bit
```haskell
Data/Aeson/Parser/Internal.hs:128:11: Suggestion: Move brackets to avoid $
Found:
  (A.satisfy $ \ w -> w == 44 || w == 125) A.<?>
    "expecting ',' or '}'"
Perhaps:
  A.satisfy (\ w -> w == 44 || w == 125) A.<?> "expecting ',' or '}'"
Data/Aeson/Parser/Internal.hs:153:13: Suggestion: Move brackets to avoid $
Found:
  (A.satisfy $ \ w -> w == 44 || w == 93) A.<?>
    "expecting ',' or ']'"
Perhaps:
  A.satisfy (\ w -> w == 44 || w == 93) A.<?> "expecting ',' or ']'"
```

**Comment by FintanH** [comment]
Sure I'll try get it done this week :ok_hand:

**Comment by FintanH** [comment]
Should be good now :smile: :crossed_fingers:

**Comment by bergmark** [comment]
Nice!

The old ghc builds started failing now... looks like we should bump the base compat lower bound to `0.10.1` to get `<>` in scope.

**Comment by FintanH** [comment]
> The old ghc builds started failing now... looks like we should bump the base compat lower bound to 0.10.1 to get <> in scope.

Since these values are definitely `String`s I'll switch it to `++` and it can be backward compat :)

**Comment by phadej** [comment]
@bergmark bumping `base-compat` won't get you `<>`.
See http://hackage.haskell.org/package/base-compat-batteries

I'm neutral on depending on `base-compat-batteries`, I guess `aeson` already depends on all of those dependencies.

**Comment by bergmark** [comment]
Ah, thanks, I misread the base-compat changelog.

I pushed a hopefully final fix, weird that it only affected GHC 7.10.

**Comment by bergmark** [comment]
re -batteries, i prefer it and would be happy to switch to it.

**Comment by FintanH** [comment]
@bergmark: This is weird, if you click "Details" to look at the progress on Travis it all looks good but GitHub doesn't seem to be picking this up :thinking:

**Comment by bergmark** [comment]
I'm guessing there was a hiccup in the travis-github integration. No worries.

**Pull request merged**
