### PR TITLE
Add MonadError Parser

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by phadej** [comment]
Alternatively, if `mtl` dependency is unwanted, specialised `catchError` would be enough to my usecase (amending error messages).

**Comment by phadej** [comment]
Ah, there is `modifyFailure`.

**Comment by phadej** [comment]
@bergmark opinions on this?

**Comment by bergmark** [comment]
This seems a bit overkill to me since we have modifyFailure. I suppose you could also add this instance locally with a newtype over Parser, or would that be terribly clunky?

**Comment by phadej** [comment]
I don't insist on this. Can we leave this open if more people will stumble on this and ask for?

**Comment by bergmark** [comment]
I think we can close this, it's the top result when searching for "mtl" or "MonadError" so hopefully people will find it!

**Pull request closed without merging**
