### PR TITLE
aeson <-> these swap

### LINKED ISSUE #776: Invert dependency with `these`
My comment on https://github.com/bos/aeson/issues/432#issuecomment-611588816 probably got unnoticed.

Making an issue out of it

The discussion about aeson These instances arose again.

What's your opinion nowadays, @bergmark. If I strip these to bare minimum, probably depending only assoc and hashable (+ GHC boot libs), would it be possible that ToJSON (These a b) etc to be moved to aeson?

Over past years my opinion become that These is a quite core type, and spreading it around would be easier if the these package become as small as possible, but I don't want make these-aeson just for few instances - I don't think it would make anything better, only increase the maintenance load.

### PR DESCRIPTION
**Pull request by phadej**
Resolves #776

The additions to `cabal.project` are temporary, can be removed after releases are done.

---

|             | aeson <1.5.1.0                                         | aeson >= 1.5.1.0         |
|-------------|--------------------------------------------------------|--------------------------|
| these <1.1  | instance in these                                      | impossible configuration |
| these >=1.1 | no aeson instance, these major bump indicates breakage | instance in aeson        |

deps2

---

Corresponding PRs:
- https://github.com/isomorphism/these/pull/143
- https://github.com/phadej/qc-instances/pull/51

### CODE REVIEW

**Comment by phadej** [comment]
The failing CI is due HLint. I'll make fixing PR soon (if no-one beats me to it).

**Comment by bergmark** [comment]
LGTM!

**Comment by phadej** [comment]
Rebased this PR on top of #779

**Comment by phadej** [comment]
And green.

Feel free to merge an release. I'll follow with corresponding `these` and `quickcheck-instances` shortly after. And will make cleanup PR after all is on Hackage.

**Comment by bergmark** [comment]
I'll make a release now.

How do you generate the dependency graphs btw?

**Comment by phadej** [comment]
With [`cabal-plan`](https://hackage.haskell.org/package/cabal-plan), it has `dot` command.

**Pull request merged**
