### PR TITLE
Add [From|To]JSON[1] instances for Data.Semigroup.* newtypes

### PR DESCRIPTION
**Pull request by lspitzner**

### CODE REVIEW

**Comment by lspitzner** [comment]
Fixes #461

**Comment by phadej** [comment]
I'd add at least example encodings to `UnitTests.hs`

**Comment by bergmark** [comment]
Yes please re tests. I'm reworking a specification for the serialization formats as mentioned in #365 so if that gets completed these tests can be added there (vacation and spotty hack time at the moment).

**Comment by lspitzner** [comment]
eh, i had some `FromJSON1`s without the corresponding `FromJSON`s.

Monoid.* had no tests, so i added those.

Just noticed the note about lossy nested Maybes. This extends to Option too then. Should that be pointed out somewhere?

Should i also write changelog entry/bump version?

**Comment by bergmark** [comment]
> Just noticed the note about lossy nested Maybes. This extends to Option too then. Should that be pointed out somewhere?

That sounds like a good thing to do.

> Should i also write changelog entry/bump version?

Changelog entries are always welcome and they can state whether the changes are breaking, but let's wait with version bumps until i do the release (I'll add this to CONTRIBUTING.md).

Thanks!

**Comment by lspitzner** [comment]
Added changelog entry.

Don't really know where to add the "lossy" documentation, as it currently seems to only be mentioned in the unittests and on the tracker. Perhaps at the module haddocks at `Data.Aeson`? (And maybe this should be handled as a separate issue, along the lines of "document how specific instances are currently implemented".)

**Comment by bergmark** [comment]
Thanks!

Short descriptions can be placed directly on the instance http://stackoverflow.com/a/21871914/182603

**Comment by lspitzner** [comment]
But [From|To]JSON[1] ~ 4 instances per type. I'll copy the same note to those instancecs; i guess that is fine if i keep the doc short.

**Comment by bergmark** [comment]
I'm not saying we should document every instance :) just unexpected things like this. The test suite is a better place to specify everything in detail.

**Pull request merged**
