### PR TITLE
Issue 406 base compat

### LINKED ISSUE #406: Use base-compat and time-locale-compat to reduce CPP
Opinions?

### PR DESCRIPTION
**Pull request by phadej**
Resolve #406

### CODE REVIEW

**Comment by bergmark** [comment]
I think we should have the Prelude.Compat import in every module, then we never have to think about this again.

**Comment by phadej** [comment]
@bergmark what about having `NoImplicitPrelude` in `aeson.cabal` ?

**Comment by bergmark** [comment]
If we do that you can no longer use plain `ghci` to load the project. `cabal repl` used to not take this into account as well IIRC (has it been fixed?). `stack ghci` does take this into account, but I have not tested how it interacts with loading multiple packages.

**Comment by phadej** [comment]
force pushed, `Prelude.Compat` is in every module now

**Comment by RyanGlScott** [comment]
BTW, I don't think you need to enable `LANGUAGE CPP` in `Data.Aeson.Parser.Time` anymore.

**Comment by phadej** [comment]
@RyanGlScott noted

**Comment by phadej** [comment]
rebased

**Pull request merged**
