### PR TITLE
Add Ord instance for JSONPathElement

### PR DESCRIPTION
**Pull request by sol**

### CODE REVIEW

**Comment by sol** [comment]
@bergmark I kind of need this urgently for `sol/hpack` and I'm not at all thrilled about making a release with an orphan instance.  Any chance we can get this on Hackage soon?

**Comment by bergmark** [comment]
Sure, I can make a release tonight.

**Comment by phadej** [comment]
@bergmark might make sense to add `Ord Result` https://hackage.haskell.org/package/aeson-1.2.3.0/docs/Data-Aeson-Types.html#t:Result  too

**Comment by phadej** [comment]
And if we on it, should there be `NFData` and `Hashable` ?

**Comment by bergmark** [comment]
I'm having a pretty busy week so I'll just ship this change now, but adding more instances sounds good!

**Comment by bergmark** [comment]
https://hackage.haskell.org/package/aeson-1.2.4.0

**Comment by sol** [comment]
@bergmark thanks a lot!

**Pull request merged**
