### PR TITLE
Fix quickcheck-2.9 support for master

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by bergmark** [comment]
this causes one of the FromJSONKey unit tests to fail for me locally.

**Comment by bergmark** [comment]
Can you also fix the import warnings this introduces please?

**Comment by phadej** [comment]
Ah.Could we revert `QuickCheck <= 2.10` bump commit, and wait until `quickcheck-instances` has lifted the bounds / made new release. I'd rather not to `CPP` to much in the test, but bump `QuickCheck` lower bound.

**Comment by bergmark** [comment]
Yeah i reverted it

**Comment by bergmark** [comment]
This is superceded by #464, right?

**Comment by phadej** [comment]
Yes it was. Thanks for merging.

**Pull request closed without merging**
