### PR TITLE
Extend omitNothingFields for Option newtype

### LINKED ISSUE #498: omitNothingFields for Option
Would it be possible to extend the behaviour of `omitNothingFields` to the `Data.Semigroups.Option` newtype `Maybe`-wrapper? "omit(Option)NothingFields"

### PR DESCRIPTION
**Pull request by Lysxia**
Resolves #498

### CODE REVIEW

**Comment by bergmark** [comment]
Thanks, looks good!

There are a few warnings from ghc and hlint, would you mind looking into those?

The other failures seem to be CPP/QuickCheck related. I'll create a PR to remove all the QuickCheck related CPP from master

**Comment by Lysxia** [comment]
The `Arbitrary (Option a)` seem to be caused by my wrong lower bounds on `quickcheck-instances`.

**Comment by Lysxia** [comment]
There's one warning left about refactoring `argsToValue` and `argsToEncoding` in TH.

**Comment by bergmark** [comment]
Merged as 4522853

**Pull request closed without merging**
